### ISSUE TITLE
Здесь и далее по коду. Что за числа?

### ISSUE THREAD

**Issue by MentorTutor** [Yu-lianka/bird_simulator#6]
https://github.com/Yu-lianka/bird_simulator/blob/f9de16099a9fc9019663ccb8082c76c0720640a7/bird_classes.py#L79

**Comment by Yu-lianka** [comment]
SCALE - размер птички по вертикали. Ширина птички это высота с коэффицентом 1.3 ; 0.5 возникает из-за того что координаты птички отсчитываются от её центра; 0+10 край экрана плюс ширина стенки. (пропишу в коде за что отвечает SCALE)

**Comment by MentorTutor** [comment]
Спасибо :)
